"""Generate Frida scripts for ObjC tracing and heap scans."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


def generate_frida_trace_script(
    symbols: str | list[str],
    output: str | Path,
    capture_returns: bool = False,
) -> dict[str, Any]:
    """Generate a Frida script that traces ObjC method implementations."""
    parsed = [_parse_objc_symbol(symbol) for symbol in _split_symbols(symbols)]
    targets = [target for target in parsed if target]
    if not targets:
        raise RuntimeError("no ObjC method symbols were parsed")
    out_path = Path(output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(_render_trace_js(targets, capture_returns=capture_returns), encoding="utf-8")
    return {
        "ok": True,
        "output": str(out_path),
        "target_count": len(targets),
        "capture_returns": capture_returns,
        "targets": targets,
    }


def generate_frida_heap_scan_script(class_name: str, output: str | Path) -> dict[str, Any]:
    """Generate a Frida script that enumerates live ObjC instances."""
    if not class_name:
        raise RuntimeError("class_name is required")
    out_path = Path(output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(_render_heap_scan_js(class_name), encoding="utf-8")
    return {
        "ok": True,
        "output": str(out_path),
        "class_name": class_name,
    }


def _split_symbols(symbols: str | list[str]) -> list[str]:
    if isinstance(symbols, list):
        return [str(symbol).strip() for symbol in symbols if str(symbol).strip()]
    return [symbol.strip() for symbol in str(symbols).split(",") if symbol.strip()]


def _parse_objc_symbol(symbol: str) -> dict[str, str] | None:
    match = re.match(r"^([+-])\[([^ \]]+)[ _]([^\]]+)\]$", symbol)
    if not match:
        return None
    kind, class_name, selector = match.groups()
    return {
        "symbol": symbol,
        "class_name": class_name,
        "method_name": f"{kind} {selector}",
    }


def _render_trace_js(targets: list[dict[str, str]], capture_returns: bool) -> str:
    targets_json = json.dumps(targets, indent=2)
    capture = "true" if capture_returns else "false"
    return f"""// Generated by ghidra-re.
// Run with: frida -n <process> -l <this-file> --runtime=v8

const targets = {targets_json};
const captureReturns = {capture};
let hitIndex = 0;

function ptrString(value) {{
  try {{
    return value ? value.toString() : null;
  }} catch (error) {{
    return null;
  }}
}}

function objcDescription(value) {{
  try {{
    if (!value || value.isNull()) return null;
    return ObjC.Object(value).toString();
  }} catch (error) {{
    return null;
  }}
}}

function installTarget(target) {{
  const cls = ObjC.classes[target.class_name];
  if (!cls) {{
    console.log("GHIDRA_FRIDA_MISSING_CLASS " + target.class_name);
    return;
  }}
  const method = cls[target.method_name];
  if (!method) {{
    console.log("GHIDRA_FRIDA_MISSING_METHOD " + target.symbol);
    return;
  }}
  Interceptor.attach(method.implementation, {{
    onEnter(args) {{
      this.ghidraHit = {{
        hit_index: hitIndex++,
        timestamp_ms: Date.now(),
        symbol: target.symbol,
        class_name: target.class_name,
        method_name: target.method_name,
        pc: ptrString(this.context.pc),
        return_address: ptrString(this.returnAddress),
        args: {{}},
        objc_args: {{}}
      }};
      for (let i = 0; i < 8; i++) {{
        this.ghidraHit.args["x" + i] = ptrString(args[i]);
        this.ghidraHit.objc_args["x" + i] = objcDescription(args[i]);
      }}
      console.log("GHIDRA_FRIDA_HIT " + JSON.stringify(this.ghidraHit));
    }},
    onLeave(retval) {{
      if (!captureReturns || !this.ghidraHit) return;
      const event = {{
        hit_index: this.ghidraHit.hit_index,
        symbol: target.symbol,
        return_value: ptrString(retval),
        return_description: objcDescription(retval)
      }};
      console.log("GHIDRA_FRIDA_RETURN " + JSON.stringify(event));
    }}
  }});
  console.log("GHIDRA_FRIDA_INSTALLED " + target.symbol);
}}

if (!ObjC.available) {{
  throw new Error("Objective-C runtime is not available in this process");
}}

for (const target of targets) {{
  installTarget(target);
}}
"""


def _render_heap_scan_js(class_name: str) -> str:
    escaped = json.dumps(class_name)
    return f"""// Generated by ghidra-re.
// Run with: frida -n <process> -l <this-file> --runtime=v8

const className = {escaped};
let count = 0;

if (!ObjC.available) {{
  throw new Error("Objective-C runtime is not available in this process");
}}

const cls = ObjC.classes[className];
if (!cls) {{
  throw new Error("Class not found: " + className);
}}

ObjC.choose(cls, {{
  onMatch(obj) {{
    count++;
    const event = {{
      class_name: className,
      pointer: obj.handle.toString(),
      description: obj.toString()
    }};
    console.log("GHIDRA_FRIDA_HEAP_OBJECT " + JSON.stringify(event));
  }},
  onComplete() {{
    console.log("GHIDRA_FRIDA_HEAP_COMPLETE " + JSON.stringify({{ class_name: className, count }}));
  }}
}});
"""
