"""Generate XPC client harness skeletons from XPC surface reports."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ghidra_re_skill.core.config import cfg


def generate_xpc_harness(
    project: str,
    program: str,
    service: str | None = None,
    protocol: str | None = None,
    xpc_surface_path: str | Path | None = None,
    output: str | Path | None = None,
) -> dict[str, Any]:
    """Generate a compilable Objective-C NSXPCConnection harness skeleton."""
    export_dir = cfg.export_dir(project, program)
    surface_path = Path(xpc_surface_path) if xpc_surface_path else export_dir / "xpc_surface.json"
    surface = _load_json(surface_path)
    selected_service = service or _first_service(surface)
    if not selected_service:
        raise RuntimeError("no service provided and no service candidate found in xpc_surface.json")
    selected_protocol = protocol or _first_protocol(surface)
    out_path = Path(output) if output else export_dir / f"{_safe_name(selected_service)}_xpc_harness.m"
    source = _render_objc_xpc_harness(
        project=project,
        program=program,
        service=selected_service,
        protocol=selected_protocol,
        surface_path=str(surface_path),
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(source, encoding="utf-8")
    return {
        "ok": True,
        "output": str(out_path),
        "project": project,
        "program": program,
        "service": selected_service,
        "protocol": selected_protocol,
        "xpc_surface": str(surface_path),
    }


def _first_service(surface: dict[str, Any]) -> str | None:
    topology = surface.get("topology_hints") if isinstance(surface.get("topology_hints"), dict) else {}
    services = topology.get("probable_services", [])
    if not isinstance(services, list):
        return None
    for item in services:
        if isinstance(item, dict) and item.get("value"):
            return str(item["value"])
    return None


def _first_protocol(surface: dict[str, Any]) -> str | None:
    topology = surface.get("topology_hints") if isinstance(surface.get("topology_hints"), dict) else {}
    interfaces = topology.get("probable_interfaces", [])
    if not isinstance(interfaces, list):
        return None
    for item in interfaces:
        name = item.get("name") if isinstance(item, dict) else item
        if not name:
            continue
        name = str(name)
        if name.startswith("s___") or name.startswith("_"):
            continue
        if name in {"BSXPCSecureCoding", "NSXPCListenerDelegate"}:
            continue
        return name
    return None


def _render_objc_xpc_harness(
    project: str,
    program: str,
    service: str,
    protocol: str | None,
    surface_path: str,
) -> str:
    protocol_line = (
        f'        Protocol *remoteProtocol = NSProtocolFromString(@"{_objc_escape(protocol)}");'
        if protocol
        else "        Protocol *remoteProtocol = nil; // TODO: set NSProtocolFromString(@\"ProtocolName\")"
    )
    interface_block = (
        """        if (remoteProtocol) {
            connection.remoteObjectInterface = [NSXPCInterface interfaceWithProtocol:remoteProtocol];
        } else {
            NSLog(@"No protocol selected; set remoteObjectInterface before invoking methods.");
        }"""
    )
    return f"""// Generated by ghidra-re from an XPC surface report.
// Project: {_comment(project)}
// Program: {_comment(program)}
// Surface: {_comment(surface_path)}
// Service: {_comment(service)}
// Protocol: {_comment(protocol)}

#import <Foundation/Foundation.h>

int main(int argc, const char * argv[]) {{
    @autoreleasepool {{
        NSString *serviceName = @"{_objc_escape(service)}";
{protocol_line}

        NSXPCConnection *connection = [[NSXPCConnection alloc] initWithMachServiceName:serviceName options:0];
{interface_block}
        connection.interruptionHandler = ^{{
            NSLog(@"XPC connection interrupted");
        }};
        connection.invalidationHandler = ^{{
            NSLog(@"XPC connection invalidated");
        }};

        [connection resume];
        NSLog(@"Created XPC connection to %@", serviceName);

        id proxy = [connection remoteObjectProxyWithErrorHandler:^(NSError *error) {{
            NSLog(@"Remote proxy error: %@", error);
        }}];
        NSLog(@"Remote proxy placeholder: %@", proxy);

        // Safety default: no remote methods are invoked automatically.
        // Cast proxy to the selected protocol and call one method only after
        // confirming entitlement requirements and safe test inputs.

        [connection invalidate];
    }}
    return 0;
}}
"""


def _objc_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _comment(value: Any) -> str:
    if value is None or value == "":
        return "<unknown>"
    return str(value)


def _safe_name(value: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in value).strip("_") or "xpc_service"


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise RuntimeError(f"missing XPC surface report: {path}")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise RuntimeError(f"failed to parse JSON at {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise RuntimeError(f"XPC surface report must be a JSON object: {path}")
    return data
