"""Main CLI for ghidra-re-skill using typer + rich.

Commands:
  bootstrap   - detect Ghidra, create workspace, write config
  doctor      - check environment
  bridge      - bridge session management subcommands
  mission     - mission management subcommands
  notes       - shared notes subcommands
  import      - import/analyze subcommands
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console

app = typer.Typer(
    name="ghidra-re",
    help="Cross-platform Ghidra reverse-engineering orchestration.",
    no_args_is_help=True,
)
bridge_app = typer.Typer(help="Bridge session management.", no_args_is_help=True)
mission_app = typer.Typer(help="Mission management.", no_args_is_help=True)
notes_app = typer.Typer(help="Shared notes management.", no_args_is_help=True)
import_app = typer.Typer(help="Import and analysis.", no_args_is_help=True)
publish_app = typer.Typer(help="Build share/install packages.", no_args_is_help=True)

app.add_typer(bridge_app, name="bridge")
app.add_typer(mission_app, name="mission")
app.add_typer(notes_app, name="notes")
app.add_typer(import_app, name="import")
app.add_typer(publish_app, name="publish")

console = Console()
err_console = Console(stderr=True)


def _die(msg: str) -> None:
    err_console.print(f"[bold red]Error:[/bold red] {msg}")
    raise typer.Exit(code=1)


def _print_json(data: object) -> None:
    console.print_json(json.dumps(data, indent=2, default=str))


# ---------------------------------------------------------------------------
# bootstrap
# ---------------------------------------------------------------------------


@app.command()
def bootstrap(
    skip_smoke_test: bool = typer.Option(False, "--skip-smoke-test", help="Skip analyzeHeadless smoke test."),
    skip_bridge_install: bool = typer.Option(False, "--skip-bridge-install", help="Skip bridge extension install."),
    no_write_config: bool = typer.Option(False, "--no-write-config", help="Do not write config file."),
    config_file: Optional[str] = typer.Option(None, "--config-file", help="Path to config file."),
) -> None:
    """Detect Ghidra/JDK, create workspace, write config, optionally install bridge."""
    from ghidra_re_skill.core.config import cfg
    from ghidra_re_skill.core.ghidra_locator import detect_ghidra_dir, detect_jdk_dir

    console.print("[bold]ghidra-re bootstrap[/bold]")

    detected_ghidra = detect_ghidra_dir()
    detected_jdk = detect_jdk_dir()

    if not detected_ghidra:
        _die("could not detect a Ghidra install; run 'ghidra-re doctor' for details")
    if not detected_jdk:
        _die("could not detect a Java 21 JDK; run 'ghidra-re doctor' for details")

    cfg.ghidra_install_dir = detected_ghidra
    cfg.ghidra_jdk = detected_jdk
    cfg._refresh_script_dirs()

    workspace = cfg.workspace
    for d in [
        workspace / "projects",
        workspace / "exports",
        workspace / "logs",
        workspace / "investigations",
        workspace / "sources",
    ]:
        d.mkdir(parents=True, exist_ok=True)

    if not no_write_config:
        import datetime

        target = Path(config_file) if config_file else cfg.config_home / "config.env"
        target.parent.mkdir(parents=True, exist_ok=True)
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        target.write_text(
            f"# Generated by ghidra-re bootstrap on {now}\n"
            f"GHIDRA_INSTALL_DIR={detected_ghidra}\n"
            f"GHIDRA_JDK={detected_jdk}\n"
            f"GHIDRA_WORKSPACE={workspace}\n",
            encoding="utf-8",
        )
        console.print(f"Config: {target}")

    if not skip_smoke_test:
        _run_smoke_test(detected_ghidra, detected_jdk)
        console.print("Smoke test: [green]passed[/green]")
    else:
        console.print("Smoke test: skipped")

    bridge_status = "skipped"
    if not skip_bridge_install:
        try:
            from ghidra_re_skill.modules.bridge import install
            install()
            bridge_status = "installed"
        except Exception as e:
            _die(f"bridge install failed: {e}")

    console.print(f"Skill root: {cfg.skill_root}")
    console.print(f"Ghidra: {detected_ghidra}")
    console.print(f"JDK: {detected_jdk}")
    console.print(f"Workspace: {workspace}")
    console.print(f"Bridge: {bridge_status}")
    console.print("[bold green]ghidra-re bootstrap complete[/bold green]")


def _run_smoke_test(ghidra_dir: Path, jdk_dir: Path) -> None:
    import subprocess
    import tempfile

    from ghidra_re_skill.core.ghidra_locator import analyze_headless_path
    from ghidra_re_skill.core.platform_helpers import is_windows

    headless = analyze_headless_path(ghidra_dir)
    if not headless:
        _die(f"analyzeHeadless not found in {ghidra_dir}")

    if is_windows():
        smoke_binary = Path("C:/Windows/System32/where.exe")
    else:
        smoke_binary = Path("/usr/bin/true")
        if not smoke_binary.exists():
            smoke_binary = Path("/bin/ls")

    if not smoke_binary.exists():
        _die("unable to find a small system binary for smoke testing")

    import os

    with tempfile.TemporaryDirectory(prefix="ghidra-re-bootstrap-") as tmp:
        project_root = Path(tmp) / "project"
        project_root.mkdir()
        java_home = str(jdk_dir)
        path_sep = ";" if sys.platform == "win32" else ":"
        env = {
            **os.environ,
            "JAVA_HOME": java_home,
            "PATH": str(jdk_dir / "bin") + path_sep + os.environ.get("PATH", ""),
        }
        result = subprocess.run(
            [
                str(headless),
                str(project_root),
                "bootstrap-smoke",
                "-import", str(smoke_binary),
                "-overwrite",
                "-noanalysis",
                "-max-cpu", "1",
                "-log", str(Path(tmp) / "bootstrap.log"),
                "-scriptlog", str(Path(tmp) / "bootstrap.script.log"),
            ],
            shell=False,
            env=env,
            capture_output=True,
        )
        if result.returncode != 0 or not (project_root / "bootstrap-smoke.gpr").exists():
            _die("analyzeHeadless smoke test failed; run 'ghidra-re doctor' for details")


# ---------------------------------------------------------------------------
# doctor
# ---------------------------------------------------------------------------


@app.command()
def doctor() -> None:
    """Check the ghidra-re environment and report issues."""
    from ghidra_re_skill.core.config import cfg
    from ghidra_re_skill.core.ghidra_locator import detect_ghidra_dir, detect_jdk_dir, is_valid_ghidra_dir, is_valid_jdk_dir
    from ghidra_re_skill.core.subprocess_utils import find_tool

    ok_count = 0
    warn_count = 0

    def record(level: str, label: str, value: str = "") -> None:
        nonlocal ok_count, warn_count
        color = "green" if level == "OK" else "yellow" if level == "WARN" else "blue"
        val_str = f": {value}" if value else ""
        console.print(f"[{color}]{level:<8}[/{color}] {label}{val_str}")
        if level == "OK":
            ok_count += 1
        elif level == "WARN":
            warn_count += 1

    console.print(f"[bold]ghidra-re doctor[/bold]")
    console.print(f"Skill root: {cfg.skill_root}")
    console.print(f"Platform: {cfg.platform}")
    console.print(f"Config home: {cfg.config_home}")
    console.print()

    if is_valid_ghidra_dir(cfg.ghidra_install_dir):
        record("OK", "Configured Ghidra", str(cfg.ghidra_install_dir))
    else:
        record("WARN", "Configured Ghidra", str(cfg.ghidra_install_dir) + " (not set or invalid)")

    if is_valid_jdk_dir(cfg.ghidra_jdk):
        record("OK", "Configured JDK", str(cfg.ghidra_jdk))
    else:
        record("WARN", "Configured JDK", str(cfg.ghidra_jdk) + " (not set or invalid)")

    detected_ghidra = detect_ghidra_dir()
    detected_jdk = detect_jdk_dir()
    if detected_ghidra:
        record("INFO", "Detected Ghidra candidate", str(detected_ghidra))
    if detected_jdk:
        record("INFO", "Detected JDK candidate", str(detected_jdk))

    python_cmd = find_tool("python3") or find_tool("python")
    if python_cmd:
        record("INFO", "Detected Python", python_cmd)
    else:
        record("WARN", "Python not found on PATH")

    gh_cmd = find_tool("gh")
    if gh_cmd:
        record("INFO", "GitHub CLI", gh_cmd)
    else:
        record("WARN", "GitHub CLI (gh) not found on PATH")

    for path in [
        cfg.workspace,
        cfg.projects_dir,
        cfg.exports_dir,
        cfg.logs_dir,
        cfg.investigations_dir,
        cfg.sources_cache_dir,
    ]:
        if path.is_dir():
            record("OK", "Directory exists", str(path))
        else:
            record("WARN", "Directory missing", str(path))

    for asset in [
        cfg.skill_root / "scripts" / "ghidra_notes_backend.py",
        cfg.skill_root / "scripts" / "ghidra_mission_backend.py",
        cfg.skill_root / "references" / "bug-hunt-patterns.json",
    ]:
        if asset.exists():
            record("OK", "Asset present", str(asset))
        else:
            record("WARN", "Asset missing", str(asset))

    for script in [
        cfg.custom_scripts_dir / "BugHuntSupport.java",
        cfg.custom_scripts_dir / "ExportAppleBundle.java",
        cfg.custom_scripts_dir / "ExportEntrypoints.java",
        cfg.custom_scripts_dir / "ExportSinks.java",
        cfg.custom_scripts_dir / "TriageBugPaths.java",
        cfg.custom_scripts_dir / "ExportFunctionDossier.java",
    ]:
        if script.exists():
            record("OK", "Ghidra script present", str(script))
        else:
            record("WARN", "Ghidra script missing", str(script))

    console.print()
    if warn_count == 0:
        console.print("[bold green]READY[/bold green]    ghidra-re looks ready to use")
    else:
        console.print("[bold yellow]ACTION[/bold yellow]   Run 'ghidra-re bootstrap' to auto-configure this machine")


# ---------------------------------------------------------------------------
# bridge subcommands
# ---------------------------------------------------------------------------


@bridge_app.command("arm")
def bridge_arm(
    project: str = typer.Argument(..., help="Ghidra project name."),
    program: str = typer.Argument("", help="Program name (optional)."),
) -> None:
    """Arm the bridge for a project."""
    from ghidra_re_skill.modules.bridge import arm

    try:
        result = arm(project, program)
        _print_json(result)
    except Exception as e:
        _die(str(e))


@bridge_app.command("disarm")
def bridge_disarm(
    session: str = typer.Option("", help="Session ID to disarm."),
    project: str = typer.Option("", help="Project name to disarm."),
    program: str = typer.Option("", help="Program name to disarm."),
) -> None:
    """Disarm the bridge session."""
    from ghidra_re_skill.modules.bridge import disarm

    try:
        result = disarm(session, project, program)
        _print_json(result)
    except Exception as e:
        _die(str(e))


@bridge_app.command("build")
def bridge_build() -> None:
    """Build the bridge Ghidra extension."""
    from ghidra_re_skill.modules.bridge import build

    try:
        zip_path = build()
        console.print(f"Built bridge extension: {zip_path}")
    except Exception as e:
        _die(str(e))


@bridge_app.command("install")
def bridge_install() -> None:
    """Build and install the bridge extension into Ghidra settings."""
    from ghidra_re_skill.modules.bridge import install

    try:
        result = install()
        _print_json(result)
    except Exception as e:
        _die(str(e))


@bridge_app.command("call")
def bridge_call(
    endpoint: str = typer.Argument(..., help="API endpoint (e.g. /session or /symbols/get)."),
    body: str = typer.Argument("{}", help="JSON body string, @file, or '-' for stdin."),
) -> None:
    """Call a bridge endpoint and print the JSON response."""
    from ghidra_re_skill.modules.bridge import call_bridge

    # Handle @file and stdin
    if body.startswith("@"):
        body_file = Path(body[1:])
        if not body_file.exists():
            _die(f"JSON body file not found: {body_file}")
        body = body_file.read_text(encoding="utf-8")
    elif body == "-":
        body = sys.stdin.read()

    try:
        result = call_bridge(endpoint, body)
        _print_json(result)
    except Exception as e:
        _die(str(e))


@bridge_app.command("status")
def bridge_status_cmd(
    body: str = typer.Argument("{}", help="Optional JSON body with session/project/program selectors."),
) -> None:
    """Show bridge status."""
    from ghidra_re_skill.modules.bridge import bridge_status

    result = bridge_status(body)
    _print_json(result)
    if not result.get("ok"):
        raise typer.Exit(code=1)


@bridge_app.command("sessions")
def bridge_sessions() -> None:
    """List all active bridge sessions."""
    from ghidra_re_skill.modules.bridge import list_sessions

    sessions = list_sessions()
    _print_json(sessions)


@bridge_app.command("health")
def bridge_health(
    session: str = typer.Option("", help="Session ID."),
    project: str = typer.Option("", help="Project name."),
    program: str = typer.Option("", help="Program name."),
) -> None:
    """Check bridge session health."""
    from ghidra_re_skill.modules.bridge import health_check

    result = health_check(session, project, program)
    _print_json(result)
    if not result.get("ok"):
        raise typer.Exit(code=1)


# ---------------------------------------------------------------------------
# mission subcommands
# ---------------------------------------------------------------------------


@mission_app.command("start")
def mission_start(
    name: str = typer.Argument(..., help="Mission name."),
    goal: str = typer.Option(..., help="Mission goal description."),
    target: list[str] = typer.Option([], help="Target binary/project:program (repeatable)."),
    seed: list[str] = typer.Option([], help="Seed (repeatable)."),
    mode: str = typer.Option("trace", help="Mission mode."),
) -> None:
    """Start a new mission."""
    from ghidra_re_skill.modules.mission import start

    try:
        result = start(name, goal, target, seed, mode)
        _print_json(result)
    except Exception as e:
        _die(str(e))


@mission_app.command("status")
def mission_status(
    name: str = typer.Argument(..., help="Mission name."),
) -> None:
    """Show mission status."""
    from ghidra_re_skill.modules.mission import status

    try:
        result = status(name)
        _print_json(result)
    except Exception as e:
        _die(str(e))


@mission_app.command("finish")
def mission_finish(
    name: str = typer.Argument(..., help="Mission name."),
) -> None:
    """Finish a mission."""
    from ghidra_re_skill.modules.mission import finish

    try:
        result = finish(name)
        _print_json(result)
    except Exception as e:
        _die(str(e))


@mission_app.command("report")
def mission_report(
    name: str = typer.Argument(..., help="Mission name."),
) -> None:
    """Render the mission report."""
    from ghidra_re_skill.modules.mission import report

    try:
        result = report(name)
        _print_json(result)
    except Exception as e:
        _die(str(e))


@mission_app.command("trace")
def mission_trace(
    name: str = typer.Argument(..., help="Mission name."),
    seed: str = typer.Argument(..., help="Seed to trace."),
) -> None:
    """Trace a seed in a mission."""
    from ghidra_re_skill.modules.mission import trace

    try:
        result = trace(name, seed)
        _print_json(result)
    except Exception as e:
        _die(str(e))


@mission_app.command("autopilot")
def mission_autopilot(
    name: str = typer.Argument(..., help="Mission name."),
) -> None:
    """Run mission autopilot."""
    from ghidra_re_skill.modules.mission import autopilot

    try:
        result = autopilot(name)
        _print_json(result)
    except Exception as e:
        _die(str(e))


# ---------------------------------------------------------------------------
# notes subcommands
# ---------------------------------------------------------------------------


@notes_app.command("add")
def notes_add(
    title: str = typer.Option(..., help="Note title."),
    body: str = typer.Option(..., help="Note body."),
    category: str = typer.Option("workflow", help="Note category."),
    target: str = typer.Option("", help="Target (project:program)."),
    mission: str = typer.Option("", help="Mission name."),
    project: str = typer.Option("", help="Project name."),
    program: str = typer.Option("", help="Program name."),
    status: str = typer.Option("open", help="Note status."),
) -> None:
    """Add a shared note."""
    from ghidra_re_skill.modules.notes import add

    try:
        result = add(
            title=title,
            body=body,
            category=category,
            target=target,
            mission_name=mission,
            project_name=project,
            program_name=program,
            status=status,
        )
        _print_json(result)
    except Exception as e:
        _die(str(e))


@notes_app.command("sync")
def notes_sync() -> None:
    """Push queued notes to GitHub and pull the latest state."""
    from ghidra_re_skill.modules.notes import sync

    try:
        result = sync()
        _print_json(result)
    except Exception as e:
        _die(str(e))


@notes_app.command("pull")
def notes_pull() -> None:
    """Pull the latest shared notes from GitHub."""
    from ghidra_re_skill.modules.notes import pull

    try:
        result = pull()
        _print_json(result)
    except Exception as e:
        _die(str(e))


@notes_app.command("status")
def notes_status_cmd() -> None:
    """Show shared notes status."""
    from ghidra_re_skill.modules.notes import notes_status

    try:
        result = notes_status()
        _print_json(result)
    except Exception as e:
        _die(str(e))


@notes_app.command("remediate")
def notes_remediate(
    note_id: str = typer.Argument(..., help="Note ID to remediate."),
    resolution: str = typer.Option("", help="Resolution description."),
    comment: str = typer.Option("", help="Optional comment."),
) -> None:
    """Mark a note as remediated."""
    from ghidra_re_skill.modules.notes import remediate

    try:
        result = remediate(note_id, resolution, comment)
        _print_json(result)
    except Exception as e:
        _die(str(e))


@notes_app.command("open-shared")
def notes_open_shared() -> None:
    """Open the shared notes issue in the default browser."""
    from ghidra_re_skill.modules.notes import open_shared

    try:
        open_shared()
    except Exception as e:
        _die(str(e))


# ---------------------------------------------------------------------------
# import subcommands
# ---------------------------------------------------------------------------


@import_app.command("analyze")
def import_analyze(
    binary: str = typer.Argument(..., help="Binary path or source:name:/path/in/image."),
    project: str = typer.Argument("", help="Ghidra project name (auto-derived if omitted)."),
) -> None:
    """Import and analyze a binary with Ghidra."""
    from ghidra_re_skill.modules.importer import import_analyze

    try:
        result = import_analyze(binary, project or None)
        _print_json(result)
        if result.get("warnings"):
            w = result["warnings"]
            if any(v for v in w.values()):
                console.print("\n[yellow]Import warnings:[/yellow]")
                if w.get("unresolved_count"):
                    console.print(
                        f"  unresolved external programs: {w['unresolved_count']} "
                        f"(system={w['unresolved_system']} private={w['unresolved_private']} "
                        f"swift_runtime={w['unresolved_swift_runtime']} other={w['unresolved_other']})"
                    )
                if w.get("symbol_length_failures"):
                    console.print(f"  overlength symbol failures: {w['symbol_length_failures']}")
                if w.get("demangle_failures"):
                    console.print(f"  demangle failures: {w['demangle_failures']}")
    except Exception as e:
        _die(str(e))


@import_app.command("macos-framework")
def import_macos_framework(
    framework: str = typer.Argument(..., help="Path to macOS framework."),
    project: str = typer.Option("", help="Ghidra project name."),
) -> None:
    """Import a macOS framework."""
    from ghidra_re_skill.modules.importer import import_macos_framework

    try:
        result = import_macos_framework(framework, project or None)
        _print_json(result)
    except Exception as e:
        _die(str(e))


@import_app.command("run-script")
def import_run_script(
    script: str = typer.Argument(..., help="Ghidra script name (e.g. ExportAppleBundle.java)."),
    project: str = typer.Argument(..., help="Ghidra project name."),
    program: str = typer.Argument("", help="Program name within the project."),
) -> None:
    """Run a Ghidra headless script against a project."""
    from ghidra_re_skill.modules.importer import run_script

    try:
        result = run_script(script, project, program or None)
        _print_json(result)
    except Exception as e:
        _die(str(e))


# ---------------------------------------------------------------------------
# install command
# ---------------------------------------------------------------------------


@app.command("install")
def install_cmd(
    host: str = typer.Option("auto", "--host", help="Target host: codex | claude | both | auto."),
    source: Optional[str] = typer.Option(None, "--source", help="Source directory to install from."),
    no_bootstrap: bool = typer.Option(False, "--no-bootstrap", help="Skip bootstrap after install."),
    skip_smoke_test: bool = typer.Option(False, "--skip-smoke-test", help="Skip smoke test in bootstrap."),
    skip_bridge_install: bool = typer.Option(False, "--skip-bridge-install", help="Skip bridge install in bootstrap."),
) -> None:
    """Install the skill into AI host directories (~/.codex/skills/ghidra-re etc.)."""
    from ghidra_re_skill.modules.publisher import install_skill

    source_path = Path(source) if source else None
    try:
        installed = install_skill(
            host=host,
            source_dir=source_path,
            run_bootstrap=not no_bootstrap,
            skip_smoke_test=skip_smoke_test,
            skip_bridge_install=skip_bridge_install,
        )
        for p in installed:
            console.print(f"install_skill: installed {p}")
    except Exception as e:
        _die(str(e))


# ---------------------------------------------------------------------------
# publish subcommands
# ---------------------------------------------------------------------------


@publish_app.command("share")
def publish_share(
    output: Optional[str] = typer.Argument(None, help="Output zip path."),
) -> None:
    """Build a cross-platform share package zip."""
    from ghidra_re_skill.modules.publisher import build_share_package

    try:
        out = build_share_package(Path(output) if output else None)
        console.print(f"Built share package: {out}")
    except Exception as e:
        _die(str(e))


@publish_app.command("mac-desktop")
def publish_mac(
    output: Optional[str] = typer.Argument(None, help="Output zip path."),
    without_ghidra_payload: bool = typer.Option(False, "--without-ghidra-payload", help="Omit embedded Ghidra."),
) -> None:
    """Build a macOS desktop share package zip."""
    from ghidra_re_skill.modules.publisher import build_mac_desktop_share_package

    try:
        out = build_mac_desktop_share_package(
            Path(output) if output else None,
            include_ghidra_payload=not without_ghidra_payload,
        )
        console.print(f"Built mac desktop share package: {out}")
    except Exception as e:
        _die(str(e))


@publish_app.command("windows-desktop")
def publish_windows(
    output: Optional[str] = typer.Argument(None, help="Output zip path."),
    ghidra_zip: Optional[str] = typer.Option(None, "--ghidra-zip", help="Path to Ghidra zip to embed."),
) -> None:
    """Build a Windows desktop share package zip."""
    from ghidra_re_skill.modules.publisher import build_windows_desktop_share_package

    try:
        out = build_windows_desktop_share_package(
            Path(output) if output else None,
            Path(ghidra_zip) if ghidra_zip else None,
        )
        console.print(f"Built windows desktop share package: {out}")
    except Exception as e:
        _die(str(e))
